Repository Macpickle/Fractal-Project, pull requests merged in 2025-03, with the labels that each got.

#21 Added Sorting Support for the catalogue
  client/src/pages/Home.js
  server/__pycache__/main.cpython-311.pyc
  server/__pycache__/main.cpython-312.pyc
  server/__pycache__/main_test.cpython-312-pytest-8.3.4.pyc
  server/database/__pycache__/database.cpython-311.pyc
  server/database/__pycache__/database.cpython-312.pyc
  server/database/database.py
  server/database/lab9TEST.py
  server/database/productData.json
  server/main_test.py
  server/models/__pycache__/__init__.cpython-311.pyc
  server/models/__pycache__/__init__.cpython-312.pyc
  server/models/catalog/__pycache__/productModel.cpython-312.pyc
  server/models/user/__pycache__/__init__.cpython-311.pyc
  server/models/user/__pycache__/__init__.cpython-312.pyc
  server/routers/__pycache__/products.cpython-311.pyc
  server/routers/__pycache__/products.cpython-312.pyc
  server/routers/products.py
Labels: bug, enhancement, help wanted

#24 Added customer wishes: color and car types for product descriptions
  server/database/test_database.py
  server/models/catalog/productClass.py
  server/models/catalog/productModel.py
Labels: enhancement

#23 added color and car type input fields for frontend, no functionallity…
  client/src/components/Create.js
  client/src/components/Modify.js
  server/__pycache__/main_test.cpython-311-pytest-7.4.2.pyc
  server/__pycache__/test_main.cpython-311-pytest-7.4.2.pyc
  server/database/__pycache__/database.cpython-311.pyc
  server/database/__pycache__/test_database.cpython-311-pytest-7.4.2.pyc
  server/database/lab9TEST.py
  server/database/productData.json
  server/main_test.py
  server/routers/__pycache__/products.cpython-311.pyc
Labels: bug, enhancement

#25 added domain specific features, like now able to add colour and vehic…
  client/src/pages/Home.js
  server/__pycache__/test_main.cpython-311-pytest-7.4.2.pyc
  server/database/__pycache__/database.cpython-311.pyc
  server/database/__pycache__/test_database.cpython-311-pytest-7.4.2.pyc
  server/database/database.py
  server/database/productData.json
  server/models/catalog/__pycache__/productModel.cpython-311.pyc
  server/routers/__pycache__/products.cpython-311.pyc
  server/routers/products.py
  server/test_main.py
Labels: bug, enhancement
